#!/bin/bash
wget -O spinalcord_results.zip https://github.com/courtois-neuromod/anat-processing/releases/download/r20210610/spinalcord_results.zip
unzip -j spinalcord_results.zip -d $HOME/spinalcord_results/

wget -O neuromod-anat-brain-qmri.zip https://github.com/courtois-neuromod/anat-processing/releases/download/r20210726/neuromod-anat-brain-qmri.zip
unzip -j neuromod-anat-brain-qmri.zip -d $HOME/neuromod-anat-brain-qmri/
